### ISSUE TITLE
@mixin flex() throws no errors when passed space seperated values

### ISSUE THREAD

**Issue by jeffkamo** [mastastealth/sass-flex-mixin#10]
It's an easy mistake to accidentally type out...

```
@include flex(1 0 auto);
```

But that doesn't actually work, as the mixin expects three separate parameters that must be comma separated. Like...

```
@include flex(1, 0, auto);
```

Is there a way to make Sass throw an error when commas are forgotten?

**Comment by Webtransformer** [comment]
Sorry... but I cant find the problem. I am getting:

`Error: wrong number of arguments (3 for 1) for `flex'
>>             @include flex(1, 0, auto);`
