### ISSUE TITLE
Should flex.scss have an underscore prefix?

### ISSUE THREAD

**Issue by ecarlisle** [mastastealth/sass-flex-mixin#24]
Hi,
Thank you for writing these mixins! I've found them very useful in my flexbox projects.  I wondered if flex.scss should be named _flex.scss to follow the SASS convention.  I currently use bower to install the package and use bower-installer to rename the file with an underscore.  It would be great if the file started with a "_" by default.

Thoughts? Thanks again for the great set of mixins!

**Comment by mastastealth** [comment]
What you say totally makes sense. I was kinda hoping one of the previous commenters would chime in with an opinion. I don't want to mess anything up for previous users, but if there isn't any issue I can totally rename the file.

**Comment by ecarlisle** [comment]
Sounds good. If you choose to rename the file, I might suggest _flexbox.scss or _flexbox_mixins.scss.
A more semantic name may make purpose clearer in a project.

Thanks again!

**Comment by tjFogarty** [comment]
Totally agree. Can't see how it'll cause any issues as `@import` should grab the file with or without the leading underscore.

**Comment by ecarlisle** [comment]
Cool, cool! Thanks and please let me know if I can make contributions.

**Comment by Beldur** [comment]
Is there a reason the file was renamed from flex to _flexbox instead from flex to _flex?
I had to change all my imports from `@import ''sass-flex-mixin/flex';` to `@import ''sass-flex-mixin/flexbox';`

**Comment by mastastealth** [comment]
@Beldur Well, as suggested above it is more "semantic" and clear what the mixin is for this way (although I guess that'd mean I'd want to change the repo name too...).

I was worried renaming would be an issue but I imagined that anyone who is already using it in a project through bower could just keep their current version. This is not an obligatory upgrade, there is no adjustments to the CSS itself, so I imagined you could just keep the project "as-is" and just get the latest for any new projects after that. I did wait a few days to get any feedback/arguments, but got none so I went forward with the decision. Sorry for the inconvenience.
