### ISSUE TITLE
Push latest revision to NPM

### ISSUE THREAD

**Issue by glsignal** [mastastealth/sass-flex-mixin#27]
Latest on NPM is still at v1.0.0, lagging behind the repo a little

:beers: for the mixin!

**Comment by peduarte** [comment]
:+1:

**Comment by Schweinepriester** [comment]
+1

**Comment by dallasnorton** [comment]
+1

**Comment by mastastealth** [comment]
DONE! Goodness I'm a horrible maintainer. xD

**Comment by glsignal** [comment]
Thanks Brian!  🎉 ✨ ❤️
