### ISSUE TITLE
Mixin does not work properly on IE10, because it should use -ms-flex prefixed properties

### ISSUE THREAD

**Issue by dariuszsikorski** [mastastealth/sass-flex-mixin#28]
Here is my test-drive page for use with sass-flex-mixin
http://prettyminimal.com/flexbox/

After checking different browsers, it seem not to work properly on Internet Explorer 10 because it uses different flexbox properties.

From Microsoft's website:
https://msdn.microsoft.com/en-us/library/dn265027(v=vs.85).aspx

For Ie10 Use:
The -ms-flex-wrap property Instead of flex-wrap property
The -ms-flex-order and flex-order properties Instead of order property.
The -ms-flex-pack property Instead of justify-content property
The -ms-flex-align property Instead of align-items property
The -ms-flex-item-align property Instead of align-self property
The -ms-flex-line-pack property Instead of align-content property

Also there is an flexyboxes app, which generate proper code including IE10 http://the-echoplex.net/flexyboxes

[edit] I have checked scss flex mixins code and there are already -ms-flex- properties implemented, so now I don't know what's the reason of this issue.

**Comment by mastastealth** [comment]
-ms prefixes are indeed here.
