### ISSUE TITLE
major version number should be bumped; renaming flex.scss was a breaking change

### ISSUE THREAD

**Issue by jedwards1211** [mastastealth/sass-flex-mixin#31]
it looks like `flex.scss` was renamed to `_flexbox.scss`.  This has broken our projects that are using webpack with sass-loader and doing

```sass
@import ~sass-flex-mixin/flex
```
The project-breaking happened spontaneously on our build server since version 1.0.2 is considered compatible with `^1.0.0`.

Thanks for these awesome mixins!

**Comment by jedwards1211** [comment]
Assuming that only Webpack users will be doing `require('sass-flex-mixin)` (or indirectly via `@import ~sass-flex-mixin` using `sass-loader`, it would be best if your `package.json` contains:
```
"main": "_flexbox.scss"
```

**Comment by fieg** [comment]
Yes, this was indeed a breaking change in a patch update. Broke our project too :(

**Comment by mastastealth** [comment]
Dang it. I knew something like this would have happened. :( My bad. Will look into it.

**Comment by fieg** [comment]
I think a fix would be something like this:

1) revert the rename
2) tag a new patch version
3) reapply the rename
4) tag a new major version

**Comment by ruleb** [comment]
+1 this broke our build!

**Comment by verlok** [comment]
We solved this removing the usage of flex mixins and instead using plain CSS + adding postcss / autoprefixer in our build flow.

**Comment by jedwards1211** [comment]
@verlok it's not like this issue was difficult to fix, one just had to find and replace references to the file...switching to completely different tools isn't really a "solution", it's a non sequitur.

**Comment by verlok** [comment]
We didn't do that only for solving this, but to use the real CSS instructions in general (not only for flex), which are also supported by code-hint in editors. Also, we can decide to stop supporting IE10 tomorrow and update the code only by changing a configuration.

**Comment by jedwards1211** [comment]
Wow, not having to support IE10 sounds nice!

**Comment by mastastealth** [comment]
Per @fieg's suggestion I reverted the rename, bumped version, and republished release. Hopefully that fixes everyone's issues (or avoids future issues).
